### ISSUE TITLE
Rank Tags

### ISSUE THREAD

**Issue by aggelosQQ** [ImmaFreedomDevelopment/ImmaFreedomMod#2]
Look at @Adaptified's comment below.

@ValenciaOrange

**Comment by Adaptified** [comment]
Thats not the problem here. When a developer is supered, the super admin tag is overriding the developers tag, I changed the rank colors to look differential. 

Your issue will be edited with the correct thing.

**Comment by Adaptified** [comment]
@ValenciaOrange You are to fix this as well.

**Comment by aggelosQQ** [comment]
I still want the SA tag to be in Aqua.

**Comment by Adaptified** [comment]
@aggelosQQ It will not work with the rank scheme I have made, just give it a test and if you dont like it, the next update will revert it to the default.

**Comment by ValenciaOrange** [comment]
Its the Sequence, the Sa tag is either before or after our custom rank tag

**Comment by ValenciaOrange** [comment]
I'll update it

**Comment by Adaptified** [comment]
Good eye @ValenciaOrange, I didn't think you would notice it. Maybe you are smarter than I thought.

**Comment by aggelosQQ** [comment]
Basically, I really liked the old color system.

**Comment by ValenciaOrange** [comment]
Fixed
